### ISSUE TITLE
Positioning of search bar

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/beol#109]
see https://github.com/dhlab-basel/Knora-ui/issues/165

**Comment by kilchenmann** [comment]
There are two main issues with the styling on mobile devices:
- pages without the sidebar shouldn't have a margin from left. We set the css class .without-sidebar, but — I don't know why — it has the same margin as the content with sidebar. I will fix this.
- The position of the search-panel is wrong and too wide; we should fix the width in the knora-ui module and the position in the app

I can help to fix these issues

**Comment by tobiasschweizer** [comment]
That's great. Thank you very much!

**Comment by tobiasschweizer** [comment]
Is this related to #67?

**Comment by kilchenmann** [comment]
> Is this related to #67?

Yes
