### ISSUE TITLE
Letter: positioning of osdviewer and incoming links

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/beol#125]
There is a problem with the margin between the osdviewer and the incoming links section. This works in the resource template but not in the letter template. In the letter template, `<section>` is used.

<img width="921" alt="screen shot 2019-03-06 at 2 48 55 pm" src="https://user-images.githubusercontent.com/6000023/53885847-fed3ca00-401e-11e9-9f10-81b62c979716.png">

**Comment by SepidehAlassi** [comment]
@tobiasschweizer hmm, have you tried removing the enclosing section from images, making it simply as:
`
            <kui-still-image #OSDViewer class="osd-viewer"
                             *ngIf="resource?.incomingStillImageRepresentations?.length > 0;"
                             [images]="resource?.stillImageRepresentationsToDisplay">
            </kui-still-image>`

It seems like when the image exceeds the dimension of the section, the location of succeeding components are not adapted.

**Comment by tobiasschweizer** [comment]
I will try that, thx!

**Comment by SepidehAlassi** [comment]
Sorry, I have not downloaded the new BEBB data yet, otherwise, I would have tried myself.
Eduroam sucks in Library, the download would take 10 hours!

**Comment by tobiasschweizer** [comment]
> Eduroam sucks in Library

obviously github does not check for explicit language :-)

> Sorry, I have not downloaded the new BEBB data yet

no worries
