### ISSUE TITLE
person: birth place label

### ISSUE THREAD

**Issue by SepidehAlassi** [dasch-swiss/beol#126]
I just found a bug.
<img width="233" alt="screenshot 2019-03-06 19 26 13" src="https://user-images.githubusercontent.com/8567642/53907861-fc389b00-4045-11e9-9e65-05bb85daebe9.png">
In the ontology, I have made a typo when I changed the label of the place of birth. My Bad, sorry! Change in ontology would require reimport of the data, so I suggest as a workaround we hard code the label in the person template of GUI, and later for the next import fix the ontology.

**Comment by tobiasschweizer** [comment]
@SepidehAlassi Could you make a PR in Knora with the changed label and assign it to me? We wouldn't have to re-import the data but just reload it. That would not be a problem.

**Comment by SepidehAlassi** [comment]
stimmt, because it is just the label which changes not the property name. 😄 Thanks for the reminder, my brain stopped functioning last night after 12 hours of writing in the library

**Comment by tobiasschweizer** [comment]
> my brain stopped functioning last night after 12 hours of writing in the library

mine never started working
