### ISSUE TITLE
Routing issues

### ISSUE THREAD

**Issue by subotic** [dasch-swiss/beol#128]

**Comment by tobiasschweizer** [comment]
I have just checked iml-leonhard and it seems fine there. So something with the new Docker config?

**Comment by subotic** [comment]
Yes, I had to make some changes in the base docker image.

**Comment by subotic** [comment]
@tobiasschweizer wrote:

I still have the problem, e.g., with https://beol-test.dasch.swiss/letter/http:%2F%2Frdfh.ch%2F0801%2FNpZsD3aWQB2buNCjqRTcVw

Maybe it rewrites the params? If I reload, it looks like this: https://beol-test.dasch.swiss/letter/http:/rdfh.ch/0801/NpZsD3aWQB2buNCjqRTcVw

**Comment by subotic** [comment]
It's an issue with the used Webserver. I've opened an issue: https://github.com/PierreZ/goStatic/issues/18

If they don't provide a timely solution, I will go an look for the bug. Shouldn't be a big thing.

**Comment by tobiasschweizer** [comment]
on iml-leonhard it works fine. What's the difference?

**Comment by subotic** [comment]
The used webserver.

**Comment by subotic** [comment]
fixed in https://github.com/dhlab-basel/beol/pull/133

it's also deployed on `beol-test`.

**Comment by tobiasschweizer** [comment]
That is great! Thank you.
