### ISSUE TITLE
filter the textsearch result wrt project

### ISSUE THREAD

**Issue by SepidehAlassi** [dasch-swiss/beol#138]
search for simple text should be limited to the BEOL project!

**Comment by tobiasschweizer** [comment]
I think the possibility already exists in the search module but we may have to configure it correctly

**Comment by tobiasschweizer** [comment]
@SepidehAlassi 
I added the necessary functionality in https://github.com/dhlab-basel/Knora-ui/pull/234

Once published, we can pass the beol project Iri as a parameter to `doFullTextSearchCountQueryCountQueryResult` and  `doFullTextSearchReadResourceSequence`

**Comment by SepidehAlassi** [comment]
resolves with KnoraUI update in https://github.com/dhlab-basel/beol/pull/140
