### ISSUE TITLE
list values are always undefined

### ISSUE THREAD

**Issue by SepidehAlassi** [dasch-swiss/beol#141]
Although the listValue is correctly stored in the triplestore,
![Screenshot 2019-05-22 at 18 38 15](https://user-images.githubusercontent.com/8567642/58192332-cd36da80-7cc0-11e9-8601-2aa42fec3204.png)

Its shown as undefined in GUI
![Screenshot 2019-05-22 at 18 35 42](https://user-images.githubusercontent.com/8567642/58192221-834df480-7cc0-11e9-9826-545dfb88e68e.png)

**Comment by tobiasschweizer** [comment]
see #139

**Comment by SepidehAlassi** [comment]
resolves with KnoraUI update in https://github.com/dhlab-basel/beol/pull/140
