### ISSUE TITLE
Release BEOL 2019-08

### ISSUE THREAD

**Issue by subotic** [dasch-swiss/beol#155]
Does the BEOL app need to be re-released for Knora-API v8.1.0?

**Comment by tobiasschweizer** [comment]
I think that would be the only way to be sure that nothing breaks. So I think yes.

**Comment by tobiasschweizer** [comment]
@flavens @kilchenmann Do we need to update the version of knora-ui?

**Comment by flavens** [comment]
@tobiasschweizer Knora-UI v8.1.0 works with the latest version of Knora as well as v8.2.0 but I cannot be so sure about the previous versions..

**Comment by tobiasschweizer** [comment]
So we should update Knora-ui and see if everything is ok? Could we do that on Monday?

**Comment by kilchenmann** [comment]
@tobiasschweizer yes we can help with the update next Monday

**Comment by tobiasschweizer** [comment]
Thank you! 🙏
