### ISSUE TITLE
bug: Link icon missing

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/beol#159]
Some icons are not displayed correctly.

Spotted on this letter: http://localhost:4200/newtonLetter/http:%2F%2Frdfh.ch%2F0801%2F3RV3XIMAQBK4COUNw2zL3w

Error message in the browser's console:
<img width="773" alt="Screen Shot 2019-09-10 at 09 02 37" src="https://user-images.githubusercontent.com/29532462/64591385-f2ec0a80-d3a9-11e9-89f4-30aca3704e3c.png">

In Chrome:
<img width="1049" alt="Screen Shot 2019-09-10 at 09 02 16" src="https://user-images.githubusercontent.com/29532462/64591406-fed7cc80-d3a9-11e9-877c-1d7bdb85df55.png">

In Safari: 
<img width="724" alt="Screen Shot 2019-09-10 at 09 02 26" src="https://user-images.githubusercontent.com/29532462/64591420-06977100-d3aa-11e9-96aa-f8d056d73b6e.png">

**Comment by SepidehAlassi** [comment]
That is not a bug Flavie. These are figures which are set to be resolved on Live server. As soon as data is on the live-server these figures are displayed. The reason behind it is that the path to these figures should be replaced by those on the newton project. Here is the resolved form of this letter on live server:
<img width="1012" alt="Screenshot 2019-09-10 10 27 42" src="https://user-images.githubusercontent.com/8567642/64601870-a27aaa00-d3b5-11e9-9984-398175991b81.png">
