### ISSUE TITLE
Search Panel CSS issue

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/beol#162]
The search panel is transparent

<img width="1255" alt="Screen Shot 2019-10-14 at 11 36 59 AM" src="https://user-images.githubusercontent.com/6000023/66742022-0857c700-ee77-11e9-8497-3d238b7c82dc.png">
 
Is there some CSS missing?

**Comment by tobiasschweizer** [comment]
@subotic Once this is fixed, we can make a new release!

**Comment by tobiasschweizer** [comment]
@kilchenmann This must have happened after v1.5.0. Maybe knora-ui 9.1.0?

**Comment by kilchenmann** [comment]
I will fix it...

**Comment by tobiasschweizer** [comment]
can be reproduced with `develop` (275a7ced66eda3255e4bce7078ccc185fe8e8435)

**Comment by kilchenmann** [comment]
There was a breaking change in the search module. We have to load the main search css on the top (angular.json) to override some material styling.

**Comment by tobiasschweizer** [comment]
> There was a breaking change in the search module. We have to load the main search css on the top (angular.json) to override some material styling.

Next time please make some kind of todo list for apps using Knora-ui so they can be adapted.
