### ISSUE TITLE
List of Abbreviations

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/beol#47]
Right column should be wider. I think this is just CSS.

![screenshot 2018-10-26 09 36 39](https://user-images.githubusercontent.com/6000023/47552276-9a805b80-d904-11e8-9b78-0dbc50d5cc84.png)

**Comment by flavens** [comment]
@tobiasschweizer wider? what's that means?

**Comment by tobiasschweizer** [comment]
the width of the right column should be extended

**Comment by kilchenmann** [comment]
It's a table. I will add a css for this table
