### ISSUE TITLE
webfonts for special characters missing in new GUI

### ISSUE THREAD

**Issue by SepidehAlassi** [dasch-swiss/beol#57]
The webfonts for special characters which are defined in CSS file beol/src/themes/beol/main.scss
are missing in new GUI. 
You can see the usage of one of them in L077
<img width="144" alt="screenshot 2018-10-26 15 53 32" src="https://user-images.githubusercontent.com/8567642/47574397-68d4b800-d937-11e8-997b-e065e365e1b5.png">

**Comment by flavens** [comment]
@SepidehAlassi the webfonts are already in the beol repo but maybe it is avoided because another main.scss exists in style/

**Comment by SepidehAlassi** [comment]
@flavens yes. this should be checked and fixed before release.
