### ISSUE TITLE
French labels in homepage

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/beol#93]
2 labels are in French instead of all other labels/descriptions/titles are in English - should not it be better to keep it homogenous?

<img width="936" alt="screen shot 2019-01-10 at 14 26 42" src="https://user-images.githubusercontent.com/29532462/50971331-104b9a80-14e4-11e9-993d-818d9d58bc0d.png">

**Comment by SepidehAlassi** [comment]
@flavens Well Leonhard Euler's Opera Omnia (LEOO) is diverse when it comes to language. Euler's correspondences were in Latin, German, French, Italian, Russian
The original correspondences in IV volume (Golbach volume) were in Latin+ German but the translation and edition were in English that is why this edition project is considered an English edition and labels are/should be all in English. 

The two editions in Leonhard Euler's Commercium Epistolicum contain correspondences which were originally in French+Latin. The edition work is done in French, hence it is considered a French edition and everything related to it should be all in French.

Next, there will be another edition project imported which is Italian, and after that another which is purely German. 

I agree that it would be better and more homogenous if all the labels were in English, but that is not what BEZ people and editors want. Basically, the editor has got the power to choose any language they want for their work, and we are forced to respect it although it does not make much sense in modern terms. For my PhD, I am working on the articles of Jacob Bernoulli, although Bernoulli had written all in Latin, the editors have divided his articles to six volumes each edited in a different language which has made my life a hell. I had to not only learn Latin, but also old-school German, French and italian!!!!

**Comment by flavens** [comment]
ok!
