### ISSUE TITLE
box size

### ISSUE THREAD

**Issue by SepidehAlassi** [dasch-swiss/beol#98]
Can you please point me to the part of the code where the size of the box for links is defined? 
As you see below, the size of the box does not match the label well. The arrow overlaps the label. I would like to fix that. 
![screenshot 2019-01-17 11 12 21](https://user-images.githubusercontent.com/8567642/51315218-923e4500-1a49-11e9-9fc5-fc133e34c22e.png)

**Comment by flavens** [comment]
@SepidehAlassi I think you can work on introduction.component.scss and increase the width of the classes `.nav.mat-list-item` AND `.nav-item`. Just make sure the size stays homogenous with the children items. Otherwise you can also increase a bit the width of `.nav-children`. I hope it helps

**Comment by SepidehAlassi** [comment]
@flavens thanks for answering, it helped. I just fixed the sizes.
